# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a037ef58539a2b11ec2c262cbc32f075718f09f08b747f122bcb61669e55d78d8d74ea355ffd42ffa9a22553cd5aed1a6035ec99516ab76f875e20d79cbc7a94

test:
  secret_key_base: 164b5e85b592fb77ff81ce2227b1c70b31515500287b2e38b68e34ed0dfc0cd3bfea05c564765bf9686d4dc5267e504b8258b3b142369059161896f8e3509ba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
